//! Key definitions based on physical keyboard layout.

/// Physical keyboard keys.
///
/// Keys are named based on their physical position on a QWERTY keyboard.
/// For character input, you should use the event's `name` field instead
/// as it respects the current keyboard layout.
#[derive(Debug, Copy, Clone, PartialEq, Eq, Hash)]
#[non_exhaustive]
pub enum Key {
    // Modifier keys
    Alt,
    AltGr,
    CapsLock,
    ControlLeft,
    ControlRight,
    /// Function key (Fn)
    Function,
    MetaLeft,
    MetaRight,
    ShiftLeft,
    ShiftRight,

    // Navigation
    UpArrow,
    DownArrow,
    LeftArrow,
    RightArrow,
    Home,
    End,
    PageUp,
    PageDown,

    // Editing
    Backspace,
    Delete,
    Insert,
    Return,
    Space,
    Tab,
    Escape,

    // Function keys
    F1,
    F2,
    F3,
    F4,
    F5,
    F6,
    F7,
    F8,
    F9,
    F10,
    F11,
    F12,
    F13,
    F14,
    F15,
    F16,
    F17,
    F18,
    F19,
    F20,

    // Number row
    Num0,
    Num1,
    Num2,
    Num3,
    Num4,
    Num5,
    Num6,
    Num7,
    Num8,
    Num9,

    // Letters (QWERTY layout positions)
    KeyA,
    KeyB,
    KeyC,
    KeyD,
    KeyE,
    KeyF,
    KeyG,
    KeyH,
    KeyI,
    KeyJ,
    KeyK,
    KeyL,
    KeyM,
    KeyN,
    KeyO,
    KeyP,
    KeyQ,
    KeyR,
    KeyS,
    KeyT,
    KeyU,
    KeyV,
    KeyW,
    KeyX,
    KeyY,
    KeyZ,

    // Punctuation
    BackQuote,
    Minus,
    Equal,
    LeftBracket,
    RightBracket,
    BackSlash,
    SemiColon,
    Quote,
    Comma,
    Dot,
    Slash,

    // Lock keys
    NumLock,
    ScrollLock,
    PrintScreen,
    Pause,

    // Numpad
    Kp0,
    Kp1,
    Kp2,
    Kp3,
    Kp4,
    Kp5,
    Kp6,
    Kp7,
    Kp8,
    Kp9,
    KpDelete,
    KpReturn,
    KpMinus,
    KpPlus,
    KpMultiply,
    KpDivide,

    // Media keys
    VolumeUp,
    VolumeDown,
    VolumeMute,
    BrightnessUp,
    BrightnessDown,
    PreviousTrack,
    NextTrack,
    PlayPause,

    // Unknown key with raw keycode
    Unknown(u32),
}

impl Key {
    /// Convert a macOS keycode to a Key.
    #[cfg(target_os = "macos")]
    pub(crate) fn from_macos_keycode(code: u32) -> Self {
        // Keycodes from <HIToolbox/Events.h>
        match code {
            0 => Key::KeyA,
            1 => Key::KeyS,
            2 => Key::KeyD,
            3 => Key::KeyF,
            4 => Key::KeyH,
            5 => Key::KeyG,
            6 => Key::KeyZ,
            7 => Key::KeyX,
            8 => Key::KeyC,
            9 => Key::KeyV,
            11 => Key::KeyB,
            12 => Key::KeyQ,
            13 => Key::KeyW,
            14 => Key::KeyE,
            15 => Key::KeyR,
            16 => Key::KeyY,
            17 => Key::KeyT,
            18 => Key::Num1,
            19 => Key::Num2,
            20 => Key::Num3,
            21 => Key::Num4,
            22 => Key::Num6,
            23 => Key::Num5,
            24 => Key::Equal,
            25 => Key::Num9,
            26 => Key::Num7,
            27 => Key::Minus,
            28 => Key::Num8,
            29 => Key::Num0,
            30 => Key::RightBracket,
            31 => Key::KeyO,
            32 => Key::KeyU,
            33 => Key::LeftBracket,
            34 => Key::KeyI,
            35 => Key::KeyP,
            36 => Key::Return,
            37 => Key::KeyL,
            38 => Key::KeyJ,
            39 => Key::Quote,
            40 => Key::KeyK,
            41 => Key::SemiColon,
            42 => Key::BackSlash,
            43 => Key::Comma,
            44 => Key::Slash,
            45 => Key::KeyN,
            46 => Key::KeyM,
            47 => Key::Dot,
            48 => Key::Tab,
            49 => Key::Space,
            50 => Key::BackQuote,
            51 => Key::Backspace,
            53 => Key::Escape,
            55 => Key::MetaLeft,
            56 => Key::ShiftLeft,
            57 => Key::CapsLock,
            58 => Key::Alt, // Option key
            59 => Key::ControlLeft,
            60 => Key::ShiftRight,
            61 => Key::AltGr, // Right Option
            62 => Key::ControlRight,
            63 => Key::Function,
            64 => Key::F17,
            65 => Key::KpDelete,
            67 => Key::KpMultiply,
            69 => Key::KpPlus,
            71 => Key::NumLock,
            72 => Key::VolumeUp,
            73 => Key::VolumeDown,
            74 => Key::VolumeMute,
            75 => Key::KpDivide,
            76 => Key::KpReturn,
            78 => Key::KpMinus,
            79 => Key::F18,
            80 => Key::F19,
            82 => Key::Kp0,
            83 => Key::Kp1,
            84 => Key::Kp2,
            85 => Key::Kp3,
            86 => Key::Kp4,
            87 => Key::Kp5,
            88 => Key::Kp6,
            89 => Key::Kp7,
            91 => Key::Kp8,
            92 => Key::Kp9,
            96 => Key::F5,
            97 => Key::F6,
            98 => Key::F7,
            99 => Key::F3,
            100 => Key::F8,
            101 => Key::F9,
            103 => Key::F11,
            105 => Key::F13,
            106 => Key::F16,
            107 => Key::F14,
            109 => Key::F10,
            111 => Key::F12,
            113 => Key::F15,
            114 => Key::Insert, // Help key on Mac
            115 => Key::Home,
            116 => Key::PageUp,
            117 => Key::Delete,
            118 => Key::F4,
            119 => Key::End,
            120 => Key::F2,
            121 => Key::PageDown,
            122 => Key::F1,
            123 => Key::LeftArrow,
            124 => Key::RightArrow,
            125 => Key::DownArrow,
            126 => Key::UpArrow,
            _ => Key::Unknown(code),
        }
    }
}
