mod clients;
mod commands;
mod config;
mod error;
mod globe_key;
mod keyboard_listener;
mod keychain;
mod models;
mod recording;
mod setup;
mod text_paster;
mod ui;
mod updater;

/// Build the tauri-specta builder for type-safe commands and events
fn build_specta_builder() -> tauri_specta::Builder<tauri::Wry> {
    tauri_specta::Builder::<tauri::Wry>::new()
        // Commands with specta support (type-safe bindings will be generated)
        .commands(tauri_specta::collect_commands![
            // Accessibility
            commands::check_accessibility_permission,
            commands::request_accessibility_permission,
            // Microphone
            commands::check_microphone_permission,
            commands::open_microphone_settings,
            // App configuration
            commands::load_app_config,
            commands::save_app_config,
            // Provider selection
            commands::get_current_provider,
            commands::set_current_provider,
            commands::clear_current_provider,
            // OpenAI provider
            commands::load_openai_config,
            commands::save_openai_config,
            commands::delete_openai_config,
            commands::test_openai_config,
            // Azure OpenAI provider
            commands::load_azure_openai_config,
            commands::save_azure_openai_config,
            commands::delete_azure_openai_config,
            commands::test_azure_openai_config,
            // Local model provider
            commands::get_available_models,
            commands::download_model,
            commands::cancel_model_download,
            commands::delete_model,
            commands::load_model,
            commands::unload_model,
            commands::get_loaded_model,
            commands::load_local_model_config,
            commands::save_local_model_config,
            commands::delete_local_model_config,
            // Recording
            commands::stop_recording,
            commands::cancel_recording,
            commands::retry_transcription,
            commands::dismiss_error,
            commands::resize_popup_for_error,
            commands::register_audio_level_channel,
            // Updater
            updater::check_for_updates,
            // Onboarding
            commands::load_onboarding_config,
            commands::save_onboarding_step,
            commands::finish_onboarding,
            commands::skip_onboarding,
            commands::set_pending_restart,
            commands::restart_onboarding,
        ])
        // Events with specta support (type-safe bindings will be generated)
        .events(tauri_specta::collect_events![
            recording::events::RecordingStateChanged,
            // Model events (discriminated unions for state machine patterns)
            models::events::ModelDownloadStateChanged,
            models::events::ModelLoadingStateChanged,
        ])
}

pub fn run() {
    // Load environment variables from .env file
    dotenvy::dotenv().ok();

    // Initialize logging plugin with targets for development and production
    let log_plugin = tauri_plugin_log::Builder::new()
        .targets([
            tauri_plugin_log::Target::new(tauri_plugin_log::TargetKind::Stdout),
            tauri_plugin_log::Target::new(tauri_plugin_log::TargetKind::LogDir { file_name: None }),
            tauri_plugin_log::Target::new(tauri_plugin_log::TargetKind::Webview),
        ])
        .level(if cfg!(debug_assertions) {
            log::LevelFilter::Debug
        } else {
            log::LevelFilter::Info
        })
        .build();

    // Build specta builder for type-safe commands and events
    let specta_builder = build_specta_builder();

    // Export TypeScript bindings in debug mode
    #[cfg(debug_assertions)]
    specta_builder
        .export(
            specta_typescript::Typescript::default()
                .bigint(specta_typescript::BigIntExportBehavior::Number)
                .header("// @ts-nocheck\n// Auto-generated by tauri-specta. DO NOT EDIT.\n"),
            "../src/bindings.ts",
        )
        .expect("Failed to export TypeScript bindings");

    tauri::Builder::default()
        .plugin(log_plugin)
        .plugin(tauri_plugin_store::Builder::new().build())
        .plugin(tauri_plugin_updater::Builder::new().build())
        .plugin(tauri_plugin_dialog::init())
        .plugin(tauri_plugin_process::init())
        .plugin(tauri_plugin_opener::init())
        .setup(move |app| {
            // Mount specta events to Tauri (required for runtime event emission)
            specta_builder.mount_events(app);
            setup::setup_app(app)
        })
        .invoke_handler(tauri::generate_handler![
            commands::check_accessibility_permission,
            commands::request_accessibility_permission,
            commands::check_microphone_permission,
            commands::open_microphone_settings,
            commands::restart_app,
            commands::stop_recording,
            commands::cancel_recording,
            // App configuration
            commands::load_app_config,
            commands::save_app_config,
            // Provider selection
            commands::get_current_provider,
            commands::set_current_provider,
            commands::clear_current_provider,
            // OpenAI provider
            commands::load_openai_config,
            commands::save_openai_config,
            commands::delete_openai_config,
            commands::test_openai_config,
            // Azure OpenAI provider
            commands::load_azure_openai_config,
            commands::save_azure_openai_config,
            commands::delete_azure_openai_config,
            commands::test_azure_openai_config,
            // Local model provider
            commands::get_available_models,
            commands::download_model,
            commands::cancel_model_download,
            commands::delete_model,
            commands::load_model,
            commands::unload_model,
            commands::get_loaded_model,
            commands::load_local_model_config,
            commands::save_local_model_config,
            commands::delete_local_model_config,
            // Audio
            commands::register_audio_level_channel,
            // Error handling
            commands::retry_transcription,
            commands::dismiss_error,
            commands::resize_popup_for_error,
            // Updater
            updater::check_for_updates,
            // Onboarding
            commands::load_onboarding_config,
            commands::save_onboarding_step,
            commands::finish_onboarding,
            commands::skip_onboarding,
            commands::set_pending_restart,
            commands::restart_onboarding
        ])
        .run(tauri::generate_context!())
        .expect("error while running tauri application");
}
